trigger:
  branches:
    include:
      - '*'

parameters:
  - name: deployBranch
    displayName: Realizar Deploy da Branch (Não master)
    type: boolean
    default: false
  - name: runJobIntegrationsTestsInSIT
    displayName: Executar Testes de Integração em SIT
    type: boolean
    default: false
  - name: tagsIntegrationTestSIT
    displayName: Features para serem executadas em SIT
    type: string
    default: ''

variables:
  - group: Alelo Auto
  - group: minha-frota.mfe.angular.poc-unit-test
  - group: portal-minha-frota-commons-gilnei
  - name: app.testResultsFiles
    value: "**/testresults/junit/unit-test-result.xml"
  - name: app.coverageFileLocation
    value: "**/coverage/code-coverage.xml"

resources:
  repositories:
    - repository: frota-template
      type: git
      name: azure-pipelines-templates
    - repository: automation
      type: git
      name: automation-portal-alelo-auto-gilnei

extends:
  template: angular/template-mfe-v1.yml@frota-template
  parameters:
    imageName: frota/minha-frota-mfe-angular-poc-unit-test
    kustomizeImageTagReplace: node-image
    kappName: minha-frota-mfe-angular-poc-unit-test
    testResultsFiles: $(app.testResultsFiles)
    coverageFileLocation: $(app.coverageFileLocation)
    deployBranch: ${{ parameters.deployBranch }}
    nodeVersion:  '12.x'
    lockRunIntegrationTestDEV: automation_minha-frota_web_angular_mf-teste_sit
    enableRunIntegrationTest: true
    automationStepsDEV:
      - template: /utils/automation/minha-frota/selenium-java-mf-v1.yml@frota-template
        parameters:
          automationRepository: automation
          defaultRunTags: $(poc-unit-test.automation.sit.tags)
          userDefinedRunTags: ${{ parameters.tagsIntegrationTestSIT }}
          excludeTags: $(portal-minha-frota-commons-gilnei.automation.tags.exclude)
          parallelism: $(poc-unit-test.automation.parallel.threads)
          shellUrl: $(portal-minha-frota-commons-gilnei.mf-shell.url)
          mfUrlBaseOverrideProperty: urlBase.minha-frota.mfe.angular.poc-unit-test
